spring.application.name=order-service
server.port=8083
spring.datasource.url=jdbc:h2:mem:orders_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
logging.level.cl.duoc.fullstack.order_service_m4=DEBUG
